try {
    console.log('try');
} catch (error) {
    console.log('catch');
} finally{
    console.log('Finally');
}